"use client";

import { TextInput } from "@/components/detection/TextInput";
import { ResultCard } from "@/components/detection/ResultCard";
import { AnalysisLoader } from "@/components/detection/AnalysisLoader";
import { useTextDetection } from "@/hooks/useTextDetection";
import Link from "next/link";
import { AlertCircle, Link2 } from "lucide-react";

export default function TextDetectionPage() {
  const { status, result, error, progressMessage, analyze, reset } = useTextDetection();

  return (
    <main
      className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12"
      aria-labelledby="text-detection-heading"
    >
      <div className="mb-8">
        <h1 id="text-detection-heading" className="text-3xl font-bold text-white">
          Text Detection
        </h1>
        <p className="text-gray-400 mt-2">
          Paste or type text to analyze whether it was written by a human or generated by AI.
        </p>
      </div>

      <TextInput onAnalyze={analyze} isLoading={status === "loading"} />
      <div className="mt-4 rounded-xl border border-[#262626] bg-[#121212] p-4 text-sm text-gray-300 flex flex-wrap items-center justify-between gap-3">
        <p>Need to analyze a web article or platform post link instead?</p>
        <Link
          href="/detect/url"
          className="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg border border-[#333] text-gray-200 hover:text-white hover:border-[#4a4a4a] transition-colors"
        >
          <Link2 className="h-4 w-4" />
          Use URL Detection
        </Link>
      </div>

      <div className="mt-8" aria-live="polite" aria-atomic="true">
        {status === "loading" && (
          <div className="space-y-3">
            <AnalysisLoader />
            {progressMessage && <p className="text-sm text-gray-400">{progressMessage}</p>}
          </div>
        )}

        {status === "error" && error && (
          <div
            role="alert"
            className="bg-red-500/10 border border-red-500/20 rounded-xl p-4 flex items-center gap-3"
          >
            <AlertCircle className="h-5 w-5 text-red-400 flex-shrink-0" aria-hidden="true" />
            <p className="text-sm text-red-300">{error}</p>
          </div>
        )}

        {status === "success" && result && (
          <div className="space-y-4">
            <ResultCard result={result} />
            <button
              onClick={reset}
              className="text-sm text-gray-400 hover:text-gray-200 transition-colors"
            >
              Analyze another text
            </button>
          </div>
        )}
      </div>
    </main>
  );
}
